# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import models_pb2 as models__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClassifyNNStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/nn_go.ClassifyNN/GetInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=models__pb2.ServiceInfoNN.FromString,
                _registered_method=True)
        self.CreateOneTask = channel.unary_unary(
                '/nn_go.ClassifyNN/CreateOneTask',
                request_serializer=models__pb2.TaskOneRequest.SerializeToString,
                response_deserializer=models__pb2.TaskOneResponse.FromString,
                _registered_method=True)
        self.CreateBatchTask = channel.unary_unary(
                '/nn_go.ClassifyNN/CreateBatchTask',
                request_serializer=models__pb2.TaskBatchRequest.SerializeToString,
                response_deserializer=models__pb2.TaskBatchResponse.FromString,
                _registered_method=True)
        self.CreateBatchCodeTask = channel.unary_unary(
                '/nn_go.ClassifyNN/CreateBatchCodeTask',
                request_serializer=models__pb2.TaskBatchRequest.SerializeToString,
                response_deserializer=models__pb2.TaskBatchCodeResponse.FromString,
                _registered_method=True)


class ClassifyNNServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOneTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBatchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBatchCodeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifyNNServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=models__pb2.ServiceInfoNN.SerializeToString,
            ),
            'CreateOneTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOneTask,
                    request_deserializer=models__pb2.TaskOneRequest.FromString,
                    response_serializer=models__pb2.TaskOneResponse.SerializeToString,
            ),
            'CreateBatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBatchTask,
                    request_deserializer=models__pb2.TaskBatchRequest.FromString,
                    response_serializer=models__pb2.TaskBatchResponse.SerializeToString,
            ),
            'CreateBatchCodeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBatchCodeTask,
                    request_deserializer=models__pb2.TaskBatchRequest.FromString,
                    response_serializer=models__pb2.TaskBatchCodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nn_go.ClassifyNN', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nn_go.ClassifyNN', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClassifyNN(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nn_go.ClassifyNN/GetInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            models__pb2.ServiceInfoNN.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOneTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nn_go.ClassifyNN/CreateOneTask',
            models__pb2.TaskOneRequest.SerializeToString,
            models__pb2.TaskOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nn_go.ClassifyNN/CreateBatchTask',
            models__pb2.TaskBatchRequest.SerializeToString,
            models__pb2.TaskBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBatchCodeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nn_go.ClassifyNN/CreateBatchCodeTask',
            models__pb2.TaskBatchRequest.SerializeToString,
            models__pb2.TaskBatchCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
