# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'models.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmodels.proto\x12\x05nn_go\"O\n\x0eTaskOneRequest\x12\x0f\n\x07taskUID\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\"5\n\x0fTaskOneResponse\x12\x0f\n\x07taskUID\x18\x01 \x01(\t\x12\x11\n\tclassName\x18\x02 \x01(\t\"R\n\x10TaskBatchRequest\x12\x0f\n\x07taskUID\x18\x01 \x01(\t\x12\x0e\n\x06images\x18\x02 \x03(\x0c\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\"8\n\x11TaskBatchResponse\x12\x0f\n\x07taskUID\x18\x01 \x01(\t\x12\x12\n\nclassNames\x18\x02 \x03(\t\"<\n\x15TaskBatchCodeResponse\x12\x0f\n\x07taskUID\x18\x01 \x01(\t\x12\x12\n\nclassCodes\x18\x02 \x03(\x05\"C\n\rServiceInfoNN\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\tB\x0fZ\rservice/nn_gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rservice/nn_go'
  _globals['_TASKONEREQUEST']._serialized_start=23
  _globals['_TASKONEREQUEST']._serialized_end=102
  _globals['_TASKONERESPONSE']._serialized_start=104
  _globals['_TASKONERESPONSE']._serialized_end=157
  _globals['_TASKBATCHREQUEST']._serialized_start=159
  _globals['_TASKBATCHREQUEST']._serialized_end=241
  _globals['_TASKBATCHRESPONSE']._serialized_start=243
  _globals['_TASKBATCHRESPONSE']._serialized_end=299
  _globals['_TASKBATCHCODERESPONSE']._serialized_start=301
  _globals['_TASKBATCHCODERESPONSE']._serialized_end=361
  _globals['_SERVICEINFONN']._serialized_start=363
  _globals['_SERVICEINFONN']._serialized_end=430
# @@protoc_insertion_point(module_scope)
