# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import models_pb2 as models__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x05nn_go\x1a\x0cmodels.proto\x1a\x1bgoogle/protobuf/empty.proto2\x99\x02\n\nClassifyNN\x12\x37\n\x07GetInfo\x12\x16.google.protobuf.Empty\x1a\x14.nn_go.ServiceInfoNN\x12>\n\rCreateOneTask\x12\x15.nn_go.TaskOneRequest\x1a\x16.nn_go.TaskOneResponse\x12\x44\n\x0f\x43reateBatchTask\x12\x17.nn_go.TaskBatchRequest\x1a\x18.nn_go.TaskBatchResponse\x12L\n\x13\x43reateBatchCodeTask\x12\x17.nn_go.TaskBatchRequest\x1a\x1c.nn_go.TaskBatchCodeResponseB\x0fZ\rservice/nn_gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rservice/nn_go'
  _globals['_CLASSIFYNN']._serialized_start=67
  _globals['_CLASSIFYNN']._serialized_end=348
# @@protoc_insertion_point(module_scope)
